import { ActivityRecord } from '../models/activity-record.model';

export const ACTIVITY_MOCK_DATA: ActivityRecord[] = [
  {
    id: 1,
    time: '06:05',
    containerCode: 'CNT-00481',
    profileCode: 'P-36',
    action: 'RECEPTION',
    quantities: '120 pcs',
    status: 'RECEIVED',
  },
  {
    id: 2,
    time: '06:42',
    containerCode: 'CNT-00482',
    profileCode: 'P-37',
    action: 'RECEPTION',
    quantities: '98 pcs',
    status: 'IN_CUTTING',
  },
  {
    id: 3,
    time: '07:15',
    containerCode: 'CNT-00483',
    profileCode: 'P-38',
    action: 'CUT',
    quantities: '85 pcs',
    status: 'CUT',
  },
  {
    id: 4,
    time: '08:03',
    containerCode: 'CNT-00484',
    profileCode: 'P-36',
    action: 'CUT',
    quantities: '110 pcs',
    status: 'SENT_TO_MOLDING',
  },
  {
    id: 5,
    time: '09:20',
    containerCode: 'CNT-00485',
    profileCode: 'P-37',
    action: 'SCRAP',
    quantities: '12 pcs',
    status: 'CLOSED',
  },
  {
    id: 6,
    time: '10:45',
    containerCode: 'CNT-00486',
    profileCode: 'P-38',
    action: 'MOLDING_OUTPUT',
    quantities: '200 pcs',
    status: 'SENT_TO_MOLDING',
  },
  {
    id: 7,
    time: '11:30',
    containerCode: 'CNT-00487',
    profileCode: 'P-36',
    action: 'SCRAP',
    quantities: '7 pcs',
    status: 'CLOSED',
  },
  {
    id: 8,
    time: '12:58',
    containerCode: 'CNT-00488',
    profileCode: 'P-37',
    action: 'MOLDING_OUTPUT',
    quantities: '175 pcs',
    status: 'SENT_TO_MOLDING',
  },
  {
    id: 9,
    time: '13:40',
    containerCode: 'CNT-00489',
    profileCode: 'P-38',
    action: 'RECEPTION',
    quantities: '140 pcs',
    status: 'RECEIVED',
  },
  {
    id: 10,
    time: '14:00',
    containerCode: 'CNT-00490',
    profileCode: 'P-36',
    action: 'CUT',
    quantities: '93 pcs',
    status: 'IN_CUTTING',
  },
];

export const ACTIVITY_EMPTY_DATA: ActivityRecord[] = [];
